[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = "Webpage loader"
authors = ["Mariia Bilinska <mariiaklochko@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pytest = "^7.0.0"
pytest-cov = "^3.0.0"
requests = "^2.27.1"
requests-mock = "^1.9.3"

[tool.poetry.scripts]
page_loader = "page_loader.scripts.page_loader:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
